email:
  username: truonganhtuan3092@gmail.com
  password: ckkwnmtyalfzhjjv
  
spring:
  application:
    name: backend
  data:
    mongodb:
      uri: mongodb+srv://tayphuong1109:PhuongTay110903%40@javaphuongtay.qkqk0o3.mongodb.net/?retryWrites=true&w=majority&appName=JavaPhuongTay
      database: buddy_chat
# springdoc:
#   api-docs:
#     enabled: true
#   swagger-ui:
#     enabled: true