email:
  username: phuongtay713@gmail.com
  password: mlfoeesojdrbhbez
jwt:
  secret: 843567893696976453275974432697R634976R738467TR678T34865R6834R8763T478378637664538745673865783678548735687R3
  
spring:
  application:
    name: backend
  data:
    mongodb:
      uri: mongodb+srv://tayphuong1109:PhuongTay110903%40@javaphuongtay.qkqk0o3.mongodb.net/?retryWrites=true&w=majority&appName=JavaPhuongTay
      database: buddy_chat
# springdoc:
#   api-docs:
#     enabled: true
#   swagger-ui:
#     enabled: true